# Generated by Django 4.0.4 on 2022-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='static\\img\\dummyimg.png', upload_to='img'),
        ),
    ]
